apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eytpamtye-python 
  janus-idp.io/tekton: eytpamtye-python
  backstage.io/kubernetes-id: eytpamtye-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eytpamtye-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  